### ISSUE TITLE
I don't get something in the fitting faces article, does an SVM kernel when doing logistic regression really exist? Isn't it just a linear kernel?

### ISSUE THREAD

**Issue by adamhipster** [auduno/clmtools#11]
In https://www.auduno.com/2014/01/05/fitting-faces/ it states the following

> in our case we implemented a logistic regression classifier with an SVM kernel (which is what the original paper suggests)

My knowledge on classification is limited. I know what SVMs are on a high level, I know what logistic regression is. But I didn't know what a kernel was. So I looked it up and learned what it more or less is (if I remember correctly it is a dot product that somehow equates to intersecting transposed data points in an arbitrary higher dimensional space). But in *all* those explanations the words "SVM kernel" do not exist, since support vector machines use of kernel themselves such as a linear or gaussian kernel, or you name it. I searched on via Google for quite a while.

So I took a look in the source code and the word "SVM kernel" does not seem to exist. I just queried on the word "kernel".

https://github.com/auduno/clmtools/search?utf8=%E2%9C%93&q=kernel

To me it seems that the implementation in actuality is a logistic regression classifier with a linear kernel. 

My question is: is this the case? Or is there something inherent SVM-like about this particular kernel? When I look at Wikipedia, it does not mention SVM kernels: https://en.wikipedia.org/wiki/Support_vector_machine (it mentions linear kernels, etc.). But when I look at http://scikit-learn.org/stable/modules/svm.html it does mention SVM kernels but not in conjunction with logistic regression.

**Comment by auduno** [comment]
Hi, you're right, that was actually a wrong use of terms. The kernel is indeed a linear kernel, what I meant to say was that the classifier was trained using SVM methods. Thanks for the note, I'll correct that in the blog post!

**Comment by auduno** [comment]
This has now been fixed in the blog post.
