### ISSUE TITLE
Where can I download the negatives images?

### ISSUE THREAD

**Issue by swang** [auduno/clmtools#2]
Hi I am trying to run through your steps to build out a new model. There are a couple of errors but I am now stuck on the step where it cannot find anything in the "negatives" image folder. What should I put in there? Anything that is not a face or is there a dataset I have to download?

Thanks!

**Comment by auduno** [comment]
Hi, it doesn't really matter that much. I just used about 20 landscape photos I found on flickr, but probably any style of image without faces should work.
